from datetime import datetime

from pydantic import BaseModel, Field


class DataAvailability(BaseModel):
    """Indicates which FHIR resource types had data available."""

    Patient: bool = False
    Condition: bool = False
    MedicationRequest: bool = False
    Observation: bool = False
    AllergyIntolerance: bool = False


class SectionSummaries(BaseModel):
    """Individual section summaries generated by LLM."""

    demographics: str | None = None
    conditions: str | None = None
    medications: str | None = None
    observations: str | None = None
    allergies: str | None = None


class PatientSummaryResponse(BaseModel):
    """Complete patient summary response."""

    patient_id: str
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    summary: str = Field(description="Comprehensive clinical summary narrative")
    sections: SectionSummaries = Field(
        description="Individual section summaries for each resource type"
    )
    data_availability: DataAvailability = Field(
        description="Indicates which resource types had data"
    )
    processing_time_ms: int = Field(description="Total processing time in milliseconds")
    model: str = Field(description="LLM model used for generation")


class ErrorResponse(BaseModel):
    """Error response for API errors."""

    error: str
    detail: str | None = None
    patient_id: str | None = None
